### ISSUE TITLE
runtimeerror on install

### ISSUE THREAD

**Issue by anexiole** [evan/bleak_house#1]
hi there
 On my ubuntu karmic koala server, I am trying to install the bleak_house gem to my rails app.

HEre's the error I got:

mp/bleak_house/ruby-1.8.7-p174'
-%{ BUILDING SNAPSHOT }%-
build_snapshot.rb:1: warning: already initialized constant RUBY_VERSION
/usr/local/lib/ruby/1.9.1/x86_64-linux/rbconfig.rb:7: ruby lib version (1.9.1) doesn't match executable version (1.9.1p376) (RuntimeError)
    from /usr/local/lib/ruby/1.9.1/mkmf.rb:4:in `require'
    from /usr/local/lib/ruby/1.9.1/mkmf.rb:4
    from build_snapshot.rb:2:in`require'
    from build_snapshot.rb:2
-%{ BUILDING RUBY }%-
*\* Binary `ruby-bleak-house` is already available (patchlevel 905)
-%{ BUILDING SNAPSHOT }%-
build_snapshot.rb:1: warning: already initialized constant RUBY_VERSION
/usr/local/lib/ruby/1.9.1/x86_64-linux/rbconfig.rb:7: ruby lib version (1.9.1) doesn't match executable version (1.9.1p376) (RuntimeError)
    from /usr/local/lib/ruby/1.9.1/mkmf.rb:4:in `require'
    from /usr/local/lib/ruby/1.9.1/mkmf.rb:4
    from build_snapshot.rb:2:in`require'
    from build_snapshot.rb:2

Gem files will remain installed in /usr/local/lib/ruby/gems/1.9.1/gems/bleak_house-7.2 for inspection.
Results logged to /usr/local/lib/ruby/gems/1.9.1/gems/bleak_house-7.2/ext/gem_make.out

**Comment by alvaritogf** [comment]
Me too. I have set up 

> ruby -v
> ruby 1.8.8dev (2010-11-24) [i686-linux]

Runtime ERROR trace:
make[1]: Leaving directory `/tmp/bleak_house/ruby-1.8.7-p174'
-%{ BUILDING SNAPSHOT }%-
build_snapshot.rb:1: warning: already initialized constant RUBY_VERSION
/usr/local/lib/ruby/1.8/i686-linux/rbconfig.rb:7: ruby lib version (1.8.8) doesn't match executable version (1.8.8dev) (RuntimeError)

Does it only work for Ruby 1.8.7?

Thanks,
