### ISSUE TITLE
issue with installtion in Red Hat

### ISSUE THREAD

**Issue by Senthil-srishti** [evan/bleak_house#5]
Hi ,

I already have valgrind. but bleak house is not installing. It throws the following error, Please help me to resolve this error.

configure: error: valgrind support requested but valgrind not found
Failed: "env INSTALL_SCRIPT=\"/usr/bin/install -c\" DEFS=\"\" PACKAGE_VERSION=\"\" GREP=\"/bin/grep\" EXPORT_PREFIX=\"\" COMMON_LIBS=\"\" AR=\"ar\" MANTYPE=\"doc\" RDOCTARGET=\"\" PACKAGE_STRING=\"\" AS=\"as\" DLDFLAGS=\"\" LIBRUBYARG=\"-lruby-static\" PATH_SEPARATOR=\":\" RUBY_INSTALL_NAME=\"ruby\" PACKAGE_NAME=\"\" LN_S=\"ln -s\" EXTSTATIC=\"\" EXEEXT=\"\" YACC=\"bison -y\" LIBPATHENV=\"LD_LIBRARY_PATH\" DLEXT2=\"\" LIBS=\"-lrt -ldl -lcrypt -lm \" RUBY_SO_NAME=\"ruby\" ECHO_C=\"\" OBJDUMP=\"\" NROFF=\"/usr/bin/nroff\" CC=\"gcc\" OUTFLAG=\"-o \" STATIC=\"\" PREP=\"miniruby\" MAKEFILES=\"Makefile\" LIBRUBYARG_SHARED=\"-Wl,-R -Wl,/opt/ruby/lib -L/opt/ruby/lib \" YFLAGS=\"\" STRIP=\"strip -S -x\" MINOR=\"8\" MAKEDIRS=\"mkdir -p\" LIBRUBY_LDSHARED=\"gcc -shared\" LDFLAGS=\"-L.  -rdynamic -Wl,-export-dynamic\" ENABLE_SHARED=\"no\" NM=\"\" DLLWRAP=\"\" CFLAGS=\"-g -O2  \" INSTALL_DATA=\"/usr/bin/install -c -m 644\" INSTALL_PROGRAM=\"/usr/bin/install -c\" DLEXT=\"so\" TEENY=\"7\" PACKAGE_BUGREPORT=\"\" CPP=\"gcc -E\" ALLOCA=\"\" LIBEXT=\"a\" LIBRUBY=\"libruby-static.a\" ECHO_N=\"-n\" SOLIBS=\"\" TRY_LINK=\"\" GNU_LD=\"yes\" MAINLIBS=\"\" CP=\"cp\" EXTOUT=\".ext\" SET_MAKE=\"\" LIBRUBYARG_STATIC=\"-lruby-static\" RUBYW_INSTALL_NAME=\"\" WINDRES=\"\" LINK_SO=\"\" ECHO_T=\"\" RPATHFLAG=\" -Wl,-R%1$-s\" DLDLIBS=\" -lc\" RANLIB=\"ranlib\" LDSHARED=\"gcc -shared\" SHELL=\"/bin/sh\" ASFLAGS=\"\" INSTALL=\"/usr/bin/install -c\" ARCHFILE=\"\" LIBRUBY_DLDFLAGS=\"\" OBJEXT=\"o\" LIBRUBY_ALIASES=\"libruby.so\" DESTDIR=\"\" RM=\"rm -f\" CCDLFLAGS=\" -fPIC\" CPPOUTFILE=\"-o conftest.i\" LIBPATHFLAG=\" -L%1$-s\" CPPFLAGS=\"  \" MAJOR=\"1\" LIBRUBY_SO=\"libruby.so.1.8.7\" EGREP=\"/bin/grep -E\" COMMON_HEADERS=\"\" COMMON_MACROS=\"\" LIBRUBY_A=\"libruby-static.a\" PACKAGE_TARNAME=\"\" ARCH_FLAG=\"\" ./configure  '--prefix=/opt/ruby' --disable-shared --enable-valgrind"

Thanks,
Senthil

**Comment by larstobi** [comment]
Senthil-srishti: did you install the valgrind-devel package?
